# Generated by Django 3.2.12 on 2023-11-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerseapp', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/images'),
        ),
    ]
